POST http://localhost:5000/register
Content-Type: application/json

{
    "username": "john",
    "email": "john@email.com",
    "password": "123456"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "john",
    "password": "123456"
}

// HELPER REQUESTS
###

// GET ALL USERS
GET http://localhost:5000/users
Content-Type: application/json

{
    "password": "Nm1006357619!"
}

###

// DELETE ALL USERS
DELETE http://localhost:5000/users
Content-Type: application/json

{
    "password": "Nm1006357619!"
}